name: 🐛 Bug Report
description: Report a reproducible bug or issue.
title: "[Bug]: "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please complete the following fields.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, app version, etc.
      placeholder: e.g. Windows 11, Chrome 125.0.1
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps lead to the bug?
      placeholder: |
        1. Go to login page
        2. Enter invalid credentials
        3. Click 'Login'
        4. See error message
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots or Additional Context
      description: Add screenshots or logs if applicable.
    validations:
      required: false
